// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9xQ17iDNXXoihbu1EtB3BKyDcyi-rcUo',
    appId: '1:649556311448:web:98d6def35366af2ceb7fed',
    messagingSenderId: '649556311448',
    projectId: 'login-sample-20335',
    authDomain: 'login-sample-20335.firebaseapp.com',
    storageBucket: 'login-sample-20335.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwCk6LruAM4GwF3P3SXuZatfNja96wWIk',
    appId: '1:649556311448:android:b3154c89e3d6cd62eb7fed',
    messagingSenderId: '649556311448',
    projectId: 'login-sample-20335',
    storageBucket: 'login-sample-20335.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpZwyhrw-qwq0MCtUHf7utxZ3Xca-CoYY',
    appId: '1:649556311448:ios:c6a31eaef39a67fdeb7fed',
    messagingSenderId: '649556311448',
    projectId: 'login-sample-20335',
    storageBucket: 'login-sample-20335.appspot.com',
    androidClientId: '649556311448-g6bvb3gfbp6bg56th9girv27u2uod07u.apps.googleusercontent.com',
    iosClientId: '649556311448-qk2hgi4lkf9l7ncicbvnrk1lelch8bmk.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleLoginSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpZwyhrw-qwq0MCtUHf7utxZ3Xca-CoYY',
    appId: '1:649556311448:ios:23fe4d9595b477d6eb7fed',
    messagingSenderId: '649556311448',
    projectId: 'login-sample-20335',
    storageBucket: 'login-sample-20335.appspot.com',
    androidClientId: '649556311448-g6bvb3gfbp6bg56th9girv27u2uod07u.apps.googleusercontent.com',
    iosClientId: '649556311448-n850n8nc5ilve27be64ftnail4029cpa.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleLoginSample.RunnerTests',
  );
}
